#!/usr/bin/env bash

# save current clipboard
xclip -sel clip -o >/tmp/old.snapfi

# run rofi for snippet selection
cat ~/.snippets | rofi -dmenu | sed 's/.*    \+//' | xclip -sel clip && xdotool key ctrl+v

# restore clipboard
cat /tmp/old.snapfi | xclip -sel clip
